# Generated by Django 5.2 on 2025-06-01 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_contact_options_remove_contact_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('site_description', models.TextField(blank=True, verbose_name='Description du site')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('contact_address', models.TextField(verbose_name='Adresse de contact')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='URL YouTube')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Analytics')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_submissions', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisateur dashboard',
                'verbose_name_plural': 'Utilisateurs dashboard',
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Vue de propriété',
                'verbose_name_plural': 'Vues de propriétés',
                'ordering': ['-timestamp'],
            },
        ),
    ]
