# Generated by Django 5.2 on 2025-06-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('properties', '0004_alter_property_options_remove_property_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
