# Generated by Django 5.2 on 2025-06-01 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='properties.property', verbose_name='Propriété'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(verbose_name='Salles de bain'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='properties/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Maison'), ('apartment', 'Appartement'), ('villa', 'Villa'), ('land', 'Terrain'), ('commercial', 'Commercial'), ('office', 'Bureau')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(verbose_name='Chambres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
